---
# tasks file for roles/memcache
- name: install memcache packages
  ansible.builtin.dnf:
    name: "{{ memcache_packages }}"
    state: latest

- name: configure memcache
  ansible.builtin.template:
    src: templates/memcached.j2
    dest: /etc/sysconfig/memcached
    owner: root
    group: root
    mode: '0644'

- name: start and enable memcache
  ansible.builtin.service:
    name: memcached
    state: started
    enabled: yes
